### ISSUE TITLE
Error in `dplyr::bind_rows()`: ! Can't combine `..1$label_value` <character> and `..6$label_value` <double>.

### ISSUE THREAD

**Issue by B-1991-ing** [funkyheatmap/funkyheatmap#4]
Hi Robrecht,

Do you have any idea about the below error?
**! Can't combine `..1$label_value` <character> and `..6$label_value` <double>.**

Only write one line, it can give me a plot.
  "Total_P",   "P",      "Total_P",           "rect",        "palette1",  lst(scale = FALSE),

But, not okay if I want to show each value as text, error happened.
"Total_P",   "P",      "Total_P",           "rect",        "palette1",  lst(scale = FALSE),
  **"Total_P",   "P",      "Total_P",           "text",        "benchmark",  lst(label = "Total_P", overlay = TRUE, size = 3, scale = FALSE),**

Best,

Bing

**Comment by B-1991-ing** [comment]
What I mainly confused is that should it be a numeric or character column that can be plotted by "**rect**" and shown also in **"text"** and coloured with the parameter **"palette"**? For example, the 5 columns of the group --- "scaling_predtime" in the example.

**Comment by rcannood** [comment]
Is this the same problem as in #5 that has now been solved?

**Comment by B-1991-ing** [comment]
yes, same as 5.

**Comment by rcannood** [comment]
Closing this issue as a duplicate
