### ISSUE TITLE
The "Score" legend and the feature requirement

### ISSUE THREAD

**Issue by B-1991-ing** [funkyheatmap/funkyheatmap#5]
Hi Robrecht,

I have a few more questions when first trying this R package.

How to calculate the **"Score"** value? Is it resulted from the parameter --- **scale column**?
<img width="206" alt="Screenshot 2023-03-08 at 22 33 19" src="https://user-images.githubusercontent.com/54441633/223855276-f89d1cf6-daf1-46a5-8c56-e00438e78038.png">

I can plotted my dataframe using geom -- "text" and "funkyrect", but I prefer to directly plot my numeric columns using the geom --- **"rect" and "text"**, like overlay the numbers on the colored rectangles(color degree is based on the numeric values). I tried to plot numeric or character columns using the geom --- **"rect" and "text"** but failed.

My current plot (partial screenshot, still unpublished data) with no numbers overlay on the funckyrects.
<img width="451" alt="Screenshot 2023-03-08 at 22 41 25" src="https://user-images.githubusercontent.com/54441633/223856727-27f1eba1-9d61-4468-ab5e-fec50f445357.png">

My expected plot, but with real numbers of each column
<img width="231" alt="Screenshot 2023-03-08 at 22 45 08" src="https://user-images.githubusercontent.com/54441633/223857445-11783692-ebb6-4c5f-b410-39a1211a0eb6.png">

Best,

Bing

**Comment by rcannood** [comment]
Hi Bing!

In the last plot you showed, these are actually two separate entries in the column info. Namely:

```
> funkyheatmap::dynbenchmark_data$column_info[33:34,]
# A tibble: 2 × 6
  group            id                                         name       geom  palette      options         
  <chr>            <chr>                                      <chr>      <chr> <chr>        <list>          
1 scaling_predtime scaling_pred_scoretime_cells1m_features100 "1m × 100" rect  scaling      <named list [1]>
2 scaling_predtime scaling_pred_scoretime_cells1m_features100 ""         text  white6black4 <named list [4]>
> funkyheatmap::dynbenchmark_data$column_info[33:34,]$options[[1]]
$scale
[1] FALSE

> funkyheatmap::dynbenchmark_data$column_info[33:34,]$options[[2]]
$label
[1] "scaling_pred_timestr_cells1m_features100"

$overlay
[1] TRUE

$size
[1] 3

$scale
[1] FALSE
```

By setting `overlay` to `TRUE`, it will overlay the text geom on top of the rect geom without switching columns.

Does this resolve your issue?

**Comment by michoug** [comment]
Hi
Yes, another column with new string/character column should be in the data frame called with the `data `parameter

while this should be in the `column_info` data frame

~id, ~group, ~name, ~geom, ~palette, ~options,
"A4", "Bio", "A4", "rect", "palette1",lst(scale =FALSE),
"A4", "Bio", "", "text","palette1",list(label = "A4_string", overlay = TRUE, size = 3, scale = FALSE),

**Comment by B-1991-ing** [comment]
But would it work if I create a new chharacter/string column, should I name it **same as the number column** or in different names?

**Comment by michoug** [comment]
no it should be another name, here in my example: A4_string

A4", "Bio", "", "text","palette1",list(label = "**A4_string**", overlay = TRUE, size = 3, scale = FALSE),

**Comment by B-1991-ing** [comment]
Okay, I will have a try. Thank you very much.

**Comment by rcannood** [comment]
Thanks for finding the solution to @B-1991-ing's issue, @michoug!

I'll consider the issue of not being able to use a numerical column for a text geom a bug. At the very least, the error message should be more informative, but ideally it should just work.

**Comment by rcannood** [comment]
#26 solves the issue when rendering non-character columns as text. The fix will be included in the next release.
